version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - wordpress
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=example_database
      - WORDPRESS_DB_HOST=terraform-20181204122157295700000001.c3drsrfy3jms.eu-west-1.rds.amazonaws.com:3306
      - WORDPRESS_DB_PASSWORD=databasepsw123
      - WORDPRESS_DB_USER=root
    restart: always
